# Generated by Django 3.2.7 on 2021-09-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0002_auto_20210927_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
